# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@gbl//licensing:licenses.bzl", "generate_license")
load("@gbl//toolchain:gbl_toolchain.bzl", "link_static_cc_library")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

generate_license(
    name = "license",
    package_name = "open-dice",
)

exports_files(glob(["include/**/*.h"]))

# TODO(b/413054304#comment5): Compile multialg opendice to support ECSDA
# (P-256, P-384) backend.
cbor_baremetal_ed25519_srcs = [
    "src/boringssl_hash_kdf_ops.c",
    "src/cbor_cert_op.c",
    "src/cbor_writer.c",
    "src/boringssl_ed25519_ops.c",
    "src/dice.c",
    "src/utils.c",
]

cbor_baremetal_ed25519_hdrs = glob(["include/**/*.h"]) + ["@gbl//libopendice:bindgen/dice/dice.h"]

cc_library(
    name = "libopen_dice_cbor_baremetal_ed25519",
    srcs = cbor_baremetal_ed25519_srcs,
    hdrs = cbor_baremetal_ed25519_hdrs,
    copts = ["-fno-lto"],
    includes = [
        "include",
        "include/dice/config/android",
        "include/dice/config/boringssl_ed25519",
    ],
    deps = [
        "@boringssl//:crypto_baremetal",
        "@gbl//libc:headers",
    ],
)

link_static_cc_library(
    name = "libopen_dice_cbor_baremetal_ed25519_static",
    cc_library = ":libopen_dice_cbor_baremetal_ed25519",
)

android_srcs = [
    "src/cbor_reader.c",
    "src/android.c",
]

android_hdrs = [
    "include/dice/android.h",
]

cc_library(
    name = "libopen_dice_android_baremetal_ed25519",
    srcs = android_srcs,
    hdrs = android_hdrs,
    copts = ["-fno-lto"],
    includes = ["include"],
    deps = [
        ":libopen_dice_cbor_baremetal_ed25519",
        "@boringssl//:crypto_baremetal",
        "@gbl//libc:headers",
    ],
)

link_static_cc_library(
    name = "libopen_dice_android_baremetal_ed25519_static",
    cc_library = ":libopen_dice_android_baremetal_ed25519",
)
