# Copyright (C) 2023 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@gbl//toolchain:licenses.bzl", "generate_license")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_applicable_licenses = [":license"],
)

# Licensing (IMPORTANT)
#
# TL;DR - only use files in the `libfdt/` subdir of this package.
#
# dtc overall is licensed under GPL, but the `libfdt/` subdir is dual-licensed
# under BSD-2-Clause as well at the option of the user. We explicitly opt for
# BSD licensing, so we CANNOT use any files outside of this directory.
generate_license(
    name = "license",
    bsd_type = "@rules_license//licenses/spdx:BSD-2-Clause",
    # Do not use the default LICENSE file as it contains both GPL and BSD
    # license texts but we are opting only for BSD.
    license_text = "BSD-2-Clause",
)

# Needed for bindgen.
# Only use files under libfdt/ - see Licensing above.
exports_files(["libfdt/libfdt.h"])

cc_library(
    name = "libfdt_c",
    # Only use files under libfdt/ - see Licensing above.
    srcs = glob(["libfdt/*.c"]),
    hdrs = glob(["libfdt/*.h"]),
    copts = [
        "-Wno-int-conversion",
        "-Wno-implicit-function-declaration",
        "-Wno-pointer-integer-compare",
    ] + select({
        # Note: `instrument.h` is our own file, not dtc. It's made available via
        # the `@gbl//libfdt:dep_headers` dependency below.
        "@gbl//toolchain:tracing_enabled": [
            "-include",
            "instrument.h",
        ],
        "//conditions:default": [],
    }),
    # Only use files under libfdt/ - see Licensing above.
    includes = ["libfdt/"],
    visibility = ["//visibility:public"],
    deps = [
        "@gbl//libc:headers",
        "@gbl//libfdt:dep_headers",
    ],
)
