# Copyright (C) 2024 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@gbl//licensing:licenses.bzl", "generate_license")
load("@rules_rust//rust:defs.bzl", "rust_library")

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

generate_license(
    name = "license",
    package_name = "smoltcp",
)

# Upstream smoltcp uses a custom script in the cargo build flow to generate a `config.rs`
# containing a set of configurations. We don't use cargo. Thus we use a pre-generated
# one.
genrule(
    name = "gen_config",
    outs = ["src/config.rs"],
    cmd = """cat <<EOT > $@
    pub const IFACE_MAX_ADDR_COUNT: usize = 2;
    pub const IFACE_MAX_MULTICAST_GROUP_COUNT: usize = 4;
    pub const IFACE_MAX_SIXLOWPAN_ADDRESS_CONTEXT_COUNT: usize = 4;
    pub const IFACE_NEIGHBOR_CACHE_COUNT: usize = 16;
    pub const IFACE_MAX_ROUTE_COUNT: usize = 2;
    pub const IFACE_MAX_PREFIX_COUNT: usize = 1;
    pub const FRAGMENTATION_BUFFER_SIZE: usize = 1500;
    pub const ASSEMBLER_MAX_SEGMENT_COUNT: usize = 4;
    pub const REASSEMBLY_BUFFER_SIZE: usize = 1500;
    pub const REASSEMBLY_BUFFER_COUNT: usize = 1;
    pub const IPV6_HBH_MAX_OPTIONS: usize = 1;
    pub const DNS_MAX_RESULT_COUNT: usize = 1;
    pub const DNS_MAX_SERVER_COUNT: usize = 1;
    pub const DNS_MAX_NAME_SIZE: usize = 255;
    pub const RPL_RELATIONS_BUFFER_COUNT: usize = 16;
    pub const RPL_PARENTS_BUFFER_COUNT: usize = 8;
EOT
    """,
)

rust_library(
    name = "smoltcp",
    srcs = glob(
        ["**/*.rs"],
    ) + [
        "src/config.rs",
    ],
    applicable_licenses = [":license"],
    crate_features = [
        "medium-ethernet",
        "proto-ipv4",
        "proto-ipv6",
        "socket",
        "socket-tcp",
        "socket-icmp",
        "socket-udp",
    ],
    crate_root = "src/lib.rs",
    data = [
        ":gen_config",
    ],
    edition = "2024",
    rustc_env = {
        "OUT_DIR": ".",
    },
    rustc_flags = [
        "-A",
        "unused_imports",
        "-A",
        "dead_code",
        "-A",
        "unreachable_patterns",
        "-A",
        "unused_variables",
        "-A",
        "unused_mut",
    ],
    # TCP in the bootloader can be a significant attack vector, only allow
    # it for dev boards.
    target_compatible_with = ["@gbl//toolchain:dev"],
    deps = [
        "@bitflags",
        "@byteorder",
        "@cfg_if",
        "@heapless",
        "@managed",
    ],
)
