# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@gbl//toolchain:gbl_workspace_util.bzl", "ANDROID_RUST_LINTS")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(
    default_applicable_licenses = ["@gbl//licensing:gbl_license"],
)

genrule(
    name = "workspace_status_env",
    outs = ["workspace_status.env"],
    cmd = """
        grep -E '^STABLE_' bazel-out/stable-status.txt |
        sed -E 's/^STABLE_([^[:space:]]+) (.*)$$/\\1=\\2/' >$@
    """,
    stamp = 1,
)

rust_library(
    name = "libbuild_number",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    rustc_env_files = [":workspace_status_env"],
    rustc_flags = ANDROID_RUST_LINTS,
    visibility = ["//visibility:public"],
)

rust_test(
    name = "libbuild_number_test",
    crate = ":libbuild_number",
    rustc_flags = ANDROID_RUST_LINTS,
    visibility = ["//visibility:public"],
)
