"""GBL."""

module(name = "gbl")

bazel_dep(
    name = "bazel_skylib",
)
bazel_dep(
    name = "googletest",
)
bazel_dep(
    name = "platforms",
)
bazel_dep(
    name = "rules_cc",
)
bazel_dep(
    name = "rules_license",
)
bazel_dep(
    name = "rules_pkg",
)
bazel_dep(
    name = "rules_python",
)
bazel_dep(
    name = "rules_shell",
)
bazel_dep(
    name = "rules_rust",
)
bazel_dep(
    name = "rules_rust_bindgen",
)

gbl_repositories_ext = use_extension(
    "//integration/aosp_uefi-gbl-mainline:workspace.bzl",
    "gbl_repositories_ext",
)
use_repo(gbl_repositories_ext, "llvm_linux_x86_64_prebuilts")
use_repo(gbl_repositories_ext, "rust_prebuilts")

local_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

gbl_new_local_repository = use_repo_rule("//toolchain:gbl_new_local_repository.bzl", "gbl_new_local_repository")

gbl_rust_crate_repository = use_repo_rule("//toolchain:gbl_new_local_repository.bzl", "gbl_rust_crate_repository")

gbl_new_local_repository(
    name = "linux_x86_64_sysroot",
    build_file = "@gbl//libboot:BUILD.linux_x86_64_sysroot.bazel",
    path = "prebuilts/kernel-build-tools/sysroots/x86_64-unknown-linux-musl",
)

gbl_new_local_repository(
    name = "bindgen",
    build_file_content = """exports_files(["bindgen"])""",
    path = "prebuilts/clang-tools/linux-x86/bin",
)

gbl_new_local_repository(
    name = "libfdt_c",
    build_file = "@gbl//libfdt:BUILD.libfdt_c.bazel",
    # The upstream build rule almost works for us, but we want to inject
    # license information and instrumentation hooks.
    exclude_files = ["BUILD.bazel"],
    path = "external/dtc",
)

gbl_new_local_repository(
    name = "libufdt_c",
    build_file = "@gbl//libfdt:BUILD.libufdt_c.bazel",
    path = "external/libufdt",
)

gbl_new_local_repository(
    name = "arm_trusted_firmware",
    build_file = "@gbl//libboot/aarch64_cache_helper:BUILD.arm_trusted_firmware.bazel",
    path = "external/arm-trusted-firmware",
)

gbl_new_local_repository(
    name = "avb",
    build_file = "@gbl//libavb:BUILD.avb.bazel",
    path = "external/avb",
)

gbl_new_local_repository(
    name = "vmm",
    build_file_content = """exports_files(glob(["**/*"]))""",
    exist_marker_path = "repo_exists",
    path = "prebuilts/vmm",
)

gbl_rust_crate_repository(
    name = "uuid",
    path = "external/rust/android-crates-io/crates/uuid",
)

gbl_rust_crate_repository(
    name = "spin",
    features = [
        "mutex",
        "spin_mutex",
    ],
    path = "external/rust/android-crates-io/crates/spin",
    rustc_flags = [
        "-A",
        "unused_imports",
        "-A",
        "mismatched_lifetime_syntaxes",
    ],
)

gbl_rust_crate_repository(
    name = "static_assertions",
    path = "external/rust/android-crates-io/crates/static_assertions",
)

gbl_rust_crate_repository(
    name = "managed",
    features = ["map"],
    path = "external/rust/android-crates-io/crates/managed",
    rustc_flags = [
        "-A",
        "unused_macros",
        "-A",
        "redundant_semicolons",
        "-A",
        "mismatched_lifetime_syntaxes",
    ],
)

gbl_rust_crate_repository(
    name = "itertools",
    features = [
        "default",
        "use_std",
        "use_alloc",
    ],
    path = "external/rust/android-crates-io/crates/itertools",
    rustc_flags = [
        "-A",
        "dead_code",
    ],
    deps = ["@either"],
)

gbl_rust_crate_repository(
    name = "itertools_noalloc",
    crate_name = "itertools",
    features = [],
    path = "external/rust/android-crates-io/crates/itertools",
    rustc_flags = [
        "-A",
        "dead_code",
    ],
    deps = ["@either_noalloc"],
)

gbl_rust_crate_repository(
    name = "either",
    features = [
        "default",
        "use_std",
    ],
    path = "external/rust/android-crates-io/crates/either",
)

gbl_rust_crate_repository(
    name = "either_noalloc",
    crate_name = "either",
    features = [],
    path = "external/rust/android-crates-io/crates/either",
)

# TODO(b/383783832): migrate to android-crates-io
gbl_new_local_repository(
    name = "smoltcp",
    build_file = "@gbl//smoltcp:BUILD.smoltcp.bazel",
    path = "external/rust/android-crates-io/crates/smoltcp",
)

gbl_rust_crate_repository(
    name = "arrayvec",
    path = "external/rust/android-crates-io/crates/arrayvec",
    rustc_flags = [
        "-A",
        "dead_code",
        "-A",
        "mismatched_lifetime_syntaxes",
    ],
)

gbl_rust_crate_repository(
    name = "downcast",
    features = [
        "default",
        "std",
    ],
    path = "external/rust/android-crates-io/crates/downcast",
)

gbl_rust_crate_repository(
    name = "fragile",
    path = "external/rust/android-crates-io/crates/fragile",
)

gbl_rust_crate_repository(
    name = "lazy_static",
    path = "external/rust/android-crates-io/crates/lazy_static",
)

gbl_rust_crate_repository(
    name = "mockall",
    path = "external/rust/android-crates-io/crates/mockall",
    proc_macro_deps = ["@mockall_derive"],
    deps = [
        "@cfg_if",
        "@downcast",
        "@fragile",
        "@lazy_static",
        "@predicates",
        "@predicates_tree",
    ],
)

gbl_rust_crate_repository(
    name = "mockall_derive",
    path = "external/rust/android-crates-io/crates/mockall_derive",
    rule = "rust_proc_macro",
    deps = [
        "@cfg_if",
        "@proc_macro2",
        "@quote",
        "@syn",
    ],
)

gbl_rust_crate_repository(
    name = "predicates",
    path = "external/rust/android-crates-io/crates/predicates",
    deps = [
        "@itertools",
        "@predicates_core",
        "@termcolor",
    ],
)

gbl_rust_crate_repository(
    name = "predicates_core",
    path = "external/rust/android-crates-io/crates/predicates-core",
)

gbl_rust_crate_repository(
    name = "predicates_tree",
    path = "external/rust/android-crates-io/crates/predicates-tree",
    deps = [
        "@predicates_core",
        "@termtree",
    ],
)

gbl_rust_crate_repository(
    name = "termcolor",
    path = "external/rust/android-crates-io/crates/termcolor",
)

gbl_rust_crate_repository(
    name = "termtree",
    path = "external/rust/android-crates-io/crates/termtree",
)

gbl_rust_crate_repository(
    name = "zune_inflate",
    features = ["gzip"],
    path = "external/rust/android-crates-io/crates/zune-inflate",
)

gbl_rust_crate_repository(
    name = "lz4_flex",
    features = ["safe-decode"],
    path = "external/rust/android-crates-io/crates/lz4_flex",
    rustc_flags = [
        "-A",
        "dead_code",
    ],
)

local_repository(
    name = "zbi",
    path = "prebuilts/fuchsia_sdk/",
)

gbl_rust_crate_repository(
    name = "zerocopy",
    features = [
        "derive",
        "simd",
        "zerocopy-derive",
    ],
    path = "external/rust/android-crates-io/crates/zerocopy",
    proc_macro_deps = ["@zerocopy_derive"],
)

gbl_rust_crate_repository(
    name = "zerocopy_derive",
    path = "external/rust/android-crates-io/crates/zerocopy-derive",
    rule = "rust_proc_macro",
    deps = [
        "@proc_macro2",
        "@quote",
        "@syn",
    ],
)

gbl_rust_crate_repository(
    name = "zeroize",
    path = "external/rust/android-crates-io/crates/zeroize",
    rustc_flags = ["--cap-lints=allow"],
)

gbl_rust_crate_repository(
    name = "bitflags",
    path = "external/rust/android-crates-io/crates/bitflags",
)

gbl_rust_crate_repository(
    name = "flagset",
    path = "external/rust/android-crates-io/crates/flagset",
)

gbl_rust_crate_repository(
    name = "byteorder",
    path = "external/rust/android-crates-io/crates/byteorder",
)

gbl_rust_crate_repository(
    name = "cfg_if",
    path = "external/rust/android-crates-io/crates/cfg-if",
)

gbl_rust_crate_repository(
    name = "crc32fast",
    # Current version of the crate doesn't compile with newer editions.
    edition = "2015",
    path = "external/rust/android-crates-io/crates/crc32fast",
    deps = ["@cfg_if"],
)

gbl_rust_crate_repository(
    name = "hex",
    features = [
        "alloc",
        "default",
        "std",
    ],
    path = "external/rust/android-crates-io/crates/hex",
)

gbl_rust_crate_repository(
    name = "quote",
    features = [
        "default",
        "proc-macro",
    ],
    path = "external/rust/android-crates-io/crates/quote",
    deps = ["@proc_macro2"],
)

gbl_rust_crate_repository(
    name = "unicode_ident",
    path = "external/rust/android-crates-io/crates/unicode-ident",
)

gbl_rust_crate_repository(
    name = "syn",
    features = [
        "clone-impls",
        "default",
        "derive",
        "extra-traits",
        "full",
        "parsing",
        "printing",
        "proc-macro",
        "quote",
        "visit",
        "visit-mut",
    ],
    path = "external/rust/android-crates-io/crates/syn",
    deps = [
        "@proc_macro2",
        "@quote",
        "@unicode_ident",
    ],
)

gbl_rust_crate_repository(
    name = "proc_macro2",
    features = [
        "default",
        "proc-macro",
        "span-locations",
    ],
    path = "external/rust/android-crates-io/crates/proc-macro2",
    deps = ["@unicode_ident"],
)

gbl_new_local_repository(
    name = "boringssl",
    build_file = "@gbl//libboringssl:BUILD.boringssl.bazel",
    exclude_files = [
        # We replace the top-level BUILD file with our own.
        "BUILD",
        # Exclude this subdir build file, otherwise it masks rules we use from
        # src/gen/sources.bzl by making them private.
        "src/BUILD.bazel",
    ],
    path = "external/boringssl",
)

gbl_new_local_repository(
    name = "open_dice",
    build_file = "@gbl//libopendice:BUILD.open_dice.bazel",
    path = "external/open-dice",
)

gbl_rust_crate_repository(
    name = "bytes",
    path = "external/rust/android-crates-io/crates/bytes",
)

gbl_rust_crate_repository(
    name = "base64",
    path = "external/rust/android-crates-io/crates/base64",
)

gbl_rust_crate_repository(
    name = "strsim",
    path = "external/rust/android-crates-io/crates/strsim",
)

gbl_rust_crate_repository(
    name = "anstyle",
    path = "external/rust/android-crates-io/crates/anstyle",
)

gbl_rust_crate_repository(
    name = "clap_lex",
    path = "external/rust/android-crates-io/crates/clap_lex",
)

gbl_rust_crate_repository(
    name = "clap_builder",
    compile_data = ["README.md"],
    features = [
        "error-context",
        "help",
        "std",
        "string",
        "suggestions",
        "usage",
    ],
    path = "external/rust/android-crates-io/crates/clap_builder",
    deps = [
        "@anstyle",
        "@clap_lex",
        "@strsim",
    ],
)

gbl_rust_crate_repository(
    name = "heck",
    path = "external/rust/android-crates-io/crates/heck",
)

gbl_rust_crate_repository(
    name = "clap_derive",
    compile_data = ["README.md"],
    path = "external/rust/android-crates-io/crates/clap_derive",
    rule = "rust_proc_macro",
    deps = [
        "@heck",
        "@proc_macro2",
        "@quote",
        "@syn",
    ],
)

gbl_rust_crate_repository(
    name = "clap",
    compile_data = ["examples/demo.md"],
    features = [
        "derive",
        "error-context",
        "help",
        "std",
        "usage",
    ],
    path = "external/rust/android-crates-io/crates/clap",
    proc_macro_deps = ["@clap_derive"],
    deps = ["@clap_builder"],
)

gbl_rust_crate_repository(
    name = "hash32",
    path = "external/rust/android-crates-io/crates/hash32",
    deps = ["@byteorder"],
)

gbl_rust_crate_repository(
    name = "heapless",
    path = "external/rust/android-crates-io/crates/heapless",
    deps = [
        "@hash32",
    ],
)

# Set up a repo to export LLVM tool/library/header/sysroot paths
gbl_llvm_prebuilts = use_repo_rule("@gbl//toolchain:gbl_workspace_util.bzl", "gbl_llvm_prebuilts")

gbl_llvm_prebuilts(name = "gbl_llvm_prebuilts")

gbl_config = use_repo_rule("@gbl//toolchain:gbl_workspace_util.bzl", "gbl_config")

gbl_config(name = "gbl_config")

# We don't register GBL toolchains here because they will be masked by toolchains from
# `build/kleaf//:` as they are registered earlier. Instead, we will pass GBL toolchains via
# bazel commandline argument "--extra_toolchains=@gbl//toolchain:all" when building GBL
# targets, which allows them to be evaluated first during toolchain resolution.
