# Copyright (C) 2024 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@gbl//toolchain:gbl_toolchain.bzl", "link_static_cc_library")
load("@gbl_llvm_prebuilts//:info.bzl", "LLVM_PREBUILTS_C_INCLUDE")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_library")
load("@rules_rust//rust:defs.bzl", "rust_library")
load("@rules_rust_bindgen//:defs.bzl", "rust_bindgen")

package(
    default_visibility = ["//visibility:public"],
)

exports_files(glob(["**/*"]))

avb_headers = [
    "libavb/avb_chain_partition_descriptor.h",
    "libavb/avb_cmdline.h",
    "libavb/avb_crypto.h",
    "libavb/avb_descriptor.h",
    "libavb/avb_footer.h",
    "libavb/avb_hash_descriptor.h",
    "libavb/avb_hashtree_descriptor.h",
    "libavb/avb_kernel_cmdline_descriptor.h",
    "libavb/avb_ops.h",
    "libavb/avb_property_descriptor.h",
    "libavb/avb_rsa.h",
    "libavb/avb_sha.h",
    "libavb/avb_slot_verify.h",
    "libavb/avb_sysdeps.h",
    "libavb/avb_util.h",
    "libavb/avb_vbmeta_image.h",
    "libavb/avb_version.h",
    "libavb/libavb.h",
    "libavb_cert/avb_cert_ops.h",
    "libavb_cert/avb_cert_types.h",
    "libavb_cert/avb_cert_validate.h",
    "libavb_cert/libavb_cert.h",
]

# The rust_bindgen rule only accepts a single header for definitions,
# so combine all the headers we care about into a single synthetic header
# and use that for bindgen.
genrule(
    name = "bindgen_unified_header",
    outs = ["bindgen_unified_header.h"],
    cmd = """
cat << EOF > $(OUTS)
/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Note: this is a generated header. Do not modify it.

#ifndef __BINDGEN_UNIFIED_HEADER_H__
#define __BINDGEN_UNIFIED_HEADER_H__

#include "libavb_cert/libavb_cert.h"
#include "libavb/avb_cmdline.h"
#include "libavb/avb_crypto_ops_impl.h"
#include "libavb/avb_rsa.h"
#include "libavb/avb_sha.h"
#include "libavb/avb_sysdeps.h"
#include "libavb/libavb.h"

#endif // __BINDGEN_UNIFIED_HEADER_H__
EOF
    """,
)

# Even though the implementation requires functions defined in libefi,
# don't add a direct dependency on libefi.
# This causes symbol collisions due to definitions used for unit tests.
#
#The solution is to add the libefi dependency in the GBL binary and let the linker
# take care of everything at the end.
cc_library(
    name = "avb_crypto_ops",
    srcs = [
        "@gbl//libavb:avb_sha.c",
    ],
    defines = ["AVB_COMPILATION"],
    deps = [
        ":headers",
        "@boringssl//:libcrypto_c_baremetal",
        "@gbl//libefi:efi_sha_header",
    ],
)

link_static_cc_library(
    name = "libavb_c_sha_staticlib",
    cc_library = ":avb_crypto_ops",
)

# Add this dependency for unit tests that should NOT depend on libefi.
# These definitions do not use the libefi provided symbols.
cc_library(
    name = "avb_crypto_ops_for_test",
    srcs = [
        "@gbl//libavb:avb_sha_for_test.c",
    ],
    deps = [
        ":headers",
        "@boringssl//:libcrypto_c_baremetal",
    ],
)

# Newer version of `rust_bindgen` requires a `cc_library` target that actually produces a static
# library instead of only headers. Thus we generate a placeholder source file to meet the
# requirement.
genrule(
    name = "bindgen_noop_cc",
    outs = ["bindgen_noop_cc.cc"],
    cmd = "touch $(OUTS)",
)

cc_library(
    name = "headers",
    srcs = [":bindgen_noop_cc"],
    hdrs = avb_headers + [
        ":bindgen_unified_header",
    ],
    defines = [
        "AVB_COMPILATION",
    ],
    includes = [
        ".",
        "libavb/boringssl/",
    ],
    deps = [
        "@boringssl//:libcrypto_c_baremetal",
        "@gbl//libavb:avb_crypto_ops_impl",
        "@gbl//libc:headers",
    ],
)

cc_library(
    name = "libavb_c",
    srcs = [
        "libavb/avb_chain_partition_descriptor.c",
        "libavb/avb_cmdline.c",
        "libavb/avb_crc32.c",
        "libavb/avb_crypto.c",
        "libavb/avb_descriptor.c",
        "libavb/avb_footer.c",
        "libavb/avb_hash_descriptor.c",
        "libavb/avb_hashtree_descriptor.c",
        "libavb/avb_kernel_cmdline_descriptor.c",
        "libavb/avb_property_descriptor.c",
        "libavb/avb_rsa.c",
        "libavb/avb_slot_verify.c",
        "libavb/avb_util.c",
        "libavb/avb_vbmeta_image.c",
        "libavb/avb_version.c",
        "libavb_cert/avb_cert_validate.c",
        # C implementations for sysdeps which cannot be implemented using Rust
        "@gbl//libavb:deps.c",
    ],
    copts = [
        "-D_FILE_OFFSET_BITS=64",
        "-D_POSIX_C_SOURCE=199309L",
        "-Wa,--noexecstack",
        "-Werror",
        "-Wall",
        "-Wextra",
        "-Wformat=2",
        "-Wmissing-prototypes",
        "-Wno-unused-parameter",
        "-ffunction-sections",
        "-g",
        "-DAVB_USE_PRINTF_LOGS",
        "-DAVB_COMPILATION",
    ],
    deps = [
        ":headers",
    ],
)

link_static_cc_library(
    name = "libavb_c_staticlib",
    cc_library = ":libavb_c",
)

rust_bindgen(
    name = "libavb_c_bindgen",
    # Flags should match Soong definition in external/avb/rust/Android.bp.
    bindgen_flags = [
        "--constified-enum-module=AvbDescriptorTag",
        "--bitfield-enum=Avb.*Flags",
        "--default-enum-style=rust",
        "--newtype-global-enum=AvbSHACtxTag",
        "--with-derive-default",
        "--with-derive-custom=Avb.*Descriptor=FromBytes,Immutable,KnownLayout",
        "--with-derive-custom=AvbVBMetaImageHeader=FromBytes,Immutable,KnownLayout",
        "--with-derive-custom=AvbCertPermanentAttributes=FromBytes,IntoBytes",
        "--with-derive-custom=AvbCertCertificate.*=FromBytes,IntoBytes",
        "--with-derive-custom=AvbCertUnlock.*=FromBytes,IntoBytes",
        "--allowlist-function=avb_abort",
        "--allowlist-function=avb_(chain_partition|hash|hashtree|kernel_cmdline|property)_descriptor_validate_and_byteswap",
        "--allowlist-function=avb_cert_(generate_unlock_challenge|validate_unlock_credential|validate_vbmeta_public_key)",
        "--allowlist-function=avb_descriptor_(foreach|validate_and_byteswap)",
        "--allowlist-function=avb_sha(256|512)_(init|update|final)",
        "--allowlist-function=avb_slot_verify(_data_calculate_vbmeta_digest|_data_free)?",
        "--allowlist-function=avb_vbmeta_image_(verify|header_to_host_byte_order)",
        "--allowlist-type=AVB_CERT_.*",
        "--allowlist-type=Avb.*Flags",
        "--allowlist-type=Avb(HashtreeErrorMode|PartitionData|SlotVerifyData|VBMetaData)",
        "--allowlist-type=Avb(ChainPartition|Hash|Hashtree|KernelCmdline)Descriptor",
        "--allowlist-type=AvbDescriptor(Tag)?",
        "--allowlist-type=AvbPropertyDescriptor",
        "--allowlist-type=AvbSHA(256|512)(Impl)?Ctx",
        "--allowlist-type=AvbSHACtxTag",
        "--allowlist-var=AVB.*",
        "--use-core",
        "--raw-line",
        """
#![cfg_attr(not(test), no_std)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use zerocopy::{Immutable, IntoBytes, FromBytes, KnownLayout};
        """,
        "--ctypes-prefix=core::ffi",
    ],
    cc_lib = "headers",
    clang_flags = [
        "-I{}".format(LLVM_PREBUILTS_C_INCLUDE),
        "-nostdinc",
    ],
    header = ":bindgen_unified_header",
)

rust_library(
    name = "avb_bindgen",
    srcs = [":libavb_c_bindgen"],
    rustc_flags = [
        "--allow=non_snake_case",
        "--allow=non_camel_case_types",
    ],
    deps = ["@zerocopy"],
)

rust_library(
    name = "avb",
    srcs = glob(["rust/src/**/*.rs"]),
    crate_features = ["uuid"],
    edition = "2021",
    deps = [
        ":avb_bindgen",
        ":libavb_c_staticlib",
        "@uuid",
        "@zerocopy",
    ],
)

rust_library(
    name = "avb_test",
    srcs = ["rust/tests/test_ops.rs"],
    crate_features = ["uuid"],
    edition = "2021",
    deps = [
        ":avb",
        "@uuid",
    ],
)

py_library(
    name = "libavbtool",
    srcs = ["avbtool.py"],
)
