# Copyright (C) 2023 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@gbl//toolchain:gbl_workspace_util.bzl", "ANDROID_RUST_LINTS")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_rust//rust:defs.bzl", "rust_library")

package(
    default_applicable_licenses = ["@gbl//:gbl_license"],
    default_visibility = ["//visibility:public"],
)

exports_files(glob(["**/*"]))

cc_library(
    name = "avb_crypto_ops_impl",
    hdrs = ["avb_crypto_ops_impl.h"],
    includes = ["."],
)

rust_library(
    name = "sysdeps",
    srcs = glob(["src/sysdeps/**/*.rs"]),
    crate_name = "avb_sysdeps",
    edition = "2021",
    rustc_flags = ANDROID_RUST_LINTS,
    deps = [
        "@avb//:avb_bindgen",
        "@gbl//libc",
    ],
)
